#
# 'docker compose up'
#

services:
  node:
    image: node:20-alpine
    container_name: laravelday2024-slides
    labels:
      - traefik.http.routers.${PROJECT_NAME}.rule=Host(`${WEB_HOST}`)
      - traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=3030
    volumes:
      - "./:/app"
    working_dir: /app
    entrypoint: ["/bin/sh","-c", "./entrypoint.sh"]
    ports:
      - ${WEB_PORT}:3030
